saas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls'))
]

web/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from web.views import account, project

app_name = 'web'

urlpatterns = [
    path('',account.index,name='index'),
    path('web/register/',account.register, name='register'),
    path('web/send_sms/',account.send_sms, name='send_sms'),
    path('web/login_sms/',account.login_sms, name='login_sms'),
    path('web/login_pwd/',account.login_pwd, name='login_pwd'),
    path('web/image_code/',account.image_code, name='image_code'),
    path('web/logout/',account.logout, name='logout'),
    path('project/list/', project.project_list, name='project_list'),
    #   我的星标项目：/project/star/my/1
    #   参与星标项目：/project/star/join/3
    re_path(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
    re_path(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar, name='project_unstar'),
]

web/templates/layout/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static "plugins/bootstrap/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "plugins/font-awesome/css/font-awesome.min.css" %}">

    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "web:index" %}">Banana2Faster</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
{#        <li class="active"><a href="#">Django文档 <span class="sr-only">(current)</span></a></li>#}
        <li><a href="{% url 'web:project_list'%}">项目管理</a></li>
        <li><a href="#">应用场景</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          {% if request.tracer.user %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.tracer.user.username }} <span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><a href="{% url "web:project_list" %}">管理中心</a></li>
            <li role="separator" class=""></li>
            <li><a href="#">设置</a></li>
            <li><a href="{% url "web:logout" %}">退 出</a></li>
          </ul>
        </li>
          {% else %}
          <li><a href="{% url 'web:login_pwd' %}">登录</a></li>
          <li><a href="{% url 'web:register'%}">注册</a></li>
          {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    {% block content %}{% endblock %}

    <script src="{% static "js/jquery-3.6.3.min.js" %}"></script>
    <script src="{% static "plugins/bootstrap/js/bootstrap.min.js" %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

web/templates/layout/manage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/manage.css' %}">
    <style>
        .navbar-av {
            border-radius: 0;
        }

        .error-msg {
            color: red;
            position: absolute;
            font-size: 13px;
            font-weight: bold;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-av">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'web:project_list' %}">Tracer</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
{#            <ul class="nav navbar-nav">#}
{#                {% all_project_list request %}#}
{##}
{#                {% if request.tracer.project %}#}
{#                    {% manage_menu_list request %}#}
{#                {% endif %}#}
{#            </ul>#}

            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">工作台</a></li>
                <li><a href="#">日历</a></li>
                <li><a href="#"><i class="fa fa-bell-o" aria-hidden="true"></i> </a></li>
                <li><a href="#"><i class="fa fa-bookmark" aria-hidden="true"></i> </a></li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.tracer.user.username }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'web:index' %}">官 网</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'web:logout' %}">退 出</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}{% endblock %}


<script src="{% static 'js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>