saas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('web.urls'))
]

web/urls.py
from django.contrib import admin
from django.urls import path, re_path,include
from web.views import account, project

app_name = 'web'

urlpatterns = [
    path('',account.index,name='index'),
    path('web/register/',account.register, name='register'),
    path('web/send_sms/',account.send_sms, name='send_sms'),
    path('web/login_sms/',account.login_sms, name='login_sms'),
    path('web/login_pwd/',account.login_pwd, name='login_pwd'),
    path('web/image_code/',account.image_code, name='image_code'),
    path('web/logout/',account.logout, name='logout'),
    path('project/list/', project.project_list, name='project_list'),
    #   我的星标项目：/project/star/my/1
    #   参与星标项目：/project/star/join/3
    re_path(r'^project/star/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_star, name='project_star'),
    re_path(r'^project/unstar/(?P<project_type>\w+)/(?P<project_id>\d+)/$', project.project_unstar, name='project_unstar'),
]

web/models.py
from django.db import models


# Create your models here.
# db_index 创建索引

class UserInfo(models.Model):
    username = models.CharField(verbose_name='用户', max_length=32, db_index=True)
    email = models.EmailField(verbose_name='邮箱', max_length=32)
    mobile = models.CharField(verbose_name='手机', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=32)
    
    # price_policy = models.ForeignKey(verbose_name='价格策略', to=PricePolicy, null=True, blank=True)

    def __str__(self):
        return self.username


class PricePolicy(models.Model):
    """价格策略"""
    category_choices = (
        (1, '个人免费版'),
        (2, 'VIP优享版'),
        (3, 'VIP尊享版')
    )
    category = models.SmallIntegerField(verbose_name='收费类型', default=1)
    title = models.CharField(verbose_name='标题', max_length=32)
    price = models.PositiveIntegerField(verbose_name='价格')  # 正整数

    project_num = models.PositiveIntegerField(verbose_name='项目数')
    project_member = models.PositiveIntegerField(verbose_name='项目成员数')
    project_space = models.PositiveIntegerField(verbose_name='单项目空间')
    project_size = models.PositiveIntegerField(verbose_name='单文件大小')

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Transaction(models.Model):
    """订单表"""
    status_choices = (
        (1, '未支付'),
        (2, '已支付'),
    )

    status = models.SmallIntegerField(verbose_name='状态', choices=status_choices)

    order = models.CharField(verbose_name='订单号', max_length=64, unique=True)  # 唯一索引

    user = models.ForeignKey(verbose_name='用户', to='UserInfo', on_delete=models.SET_NULL, blank=True, null=True)
    price_policy = models.ForeignKey(verbose_name='价格策略', to='PricePolicy', on_delete=models.SET_NULL,blank=True,
                                     null=True)

    count = models.IntegerField(verbose_name='数量（年）', help_text='0表示无限期')

    price = models.IntegerField(verbose_name='实际支付价格')

    start_datetime = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)
    end_datetime = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)

    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Project(models.Model):
    """项目表"""
    color_choices = (
        (1, '#56b8eb'),
        (2, '#f28033'),
        (3, '#ebc656'),
        (4, '#a2d148'),
        (5, '#20BFA4'),
        (6, '#7461c2'),
        (7, '#20bfa3'),
    )
    name = models.CharField(verbose_name='项目名', max_length=32)
    color = models.SmallIntegerField(verbose_name='颜色', choices=color_choices, default=1)
    desc = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)
    use_space = models.IntegerField(verbose_name='项目已使用空间', default=0)
    star = models.BooleanField(verbose_name='星标', default=False)
    
    join_count = models.SmallIntegerField(verbose_name='参与人数', default=1)
    creator = models.ForeignKey(verbose_name='创建作者',to=UserInfo,on_delete=models.SET_NULL,blank=True, null=True)
    create_datetime = models.DateTimeField(verbose_name='新创建时间', auto_now_add=True)


class ProjiectUser(models.Model):
    """参与人员表"""
    user = models.ForeignKey(verbose_name='用户', to=UserInfo, related_name='projects', on_delete=models.CASCADE)
    project = models.ForeignKey(verbose_name='项目', to=Project,on_delete=models.SET_NULL,blank=True, null=True)

    # invitee = models.ForeignKey(verbose_name='邀请者', to=UserInfo, related_name='invitees', null=True, blank=True)

    star = models.BooleanField(verbose_name='星标', default=False)

    create_datetime = models.DateTimeField(verbose_name='加入时间', auto_now_add=True)

web/templates/index.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}首页{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static "css/account.css" %}">
<style>
    img
    {
        width: 100%;
    }
</style>
{% endblock %}

{% block content %}
    <div>
        <img src="{% static 'img/index/index-1.png' %}">
        <img src="{% static 'img/index/index-2.png' %}">
        <img src="{% static 'img/index/index-3.png' %}">
        <img src="{% static 'img/index/index-4.png' %}">
    </div>
{% endblock %}

{% block js %}

{% endblock %}

web/templates/login_pwd.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}用户登陆{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static "css/account.css" %}">
    <style>
        .error-message{
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户登陆</div>
        <form method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                  <div class="form-group">
                  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                     <div class="row">
                          <div class="col-xs-6">
                              {{ field }}
                              <span class="error-message">{{ field.errors.0 }}</span>
                          </div>
                          <div class="col-xs-6">
                              <img id="imageCode" src="{% url "web:image_code" %}" title="点击刷新验证码" alt="">
                          </div>
                     </div>
                  </div>
                {% else %}
                   <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      {{ field }}
                       <span class="error-message">{{ field.errors.0 }}</span>
                  </div>
                {% endif %}
            {% endfor %}
            <div>
                <div style="float: right">
                     <a href="{% url "web:login_sms" %}">手机验证码登陆？</a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <input type="submit" class="btn btn-primary" value="登 陆">
                </div>
            </div>
        </form>

    </div>

{% endblock %}

{% block js %}

    <script>
        $('#imageCode').click(function (){
            let oldSrc = $(this).attr('src');
            $(this).attr('src', oldSrc + '?');
        })
    </script>
{% endblock %}

web/templates/login_sms.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}短信登陆{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static "css/account.css" %}">
    <style>
        .error-message{
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">手机短信登陆</div>
        <form id="smsForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                  <div class="form-group">
                  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                     <div class="row">
                          <div class="col-xs-7">
                              {{ field }}
                              <span class="error-message">{{ field.errors.0 }}</span>
                          </div>
                          <div class="col-xs-5">
                              <input id="btnSms" type="button" class="btn btn-default" value="点击获取验证码">
                          </div>
                     </div>
                  </div>
                {% else %}
                   <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      {{ field }}
                       <span class="error-message"></span>
                  </div>
                {% endif %}
            {% endfor %}
             <div>
                <div style="float: right">
                     <a href="{% url "web:login_pwd" %}">账号密码登陆？</a>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-3">
                    <input id="btnLogin" type="button" class="btn btn-primary" value="登 陆">
                </div>
            </div>
        </form>

    </div>

{% endblock %}

{% block js %}
    {#  页面加载完成之后自动执行函数  #}
    <script>
        $(function () {
            bindClickBtnSms();
            bindClickLogin();
        });

        /*点击注册绑定事件*/
        function bindClickLogin(){
            $('#btnLogin').click(function (){
                $('.error-msg').empty();
                //收集表单数据($('#regForm').serialize() 获取所有表单字段的数据 + 获取CSRF tocken)
                //发送数据到后台
                $.ajax({
                    url:"{% url "web:login_sms" %}",
                    type:"POST",
                    data: $('#smsForm').serialize(),
                    success:function (res){
                        if(res.status){
                            location.href=res.data;
                        }else {
                            $.each(res.error, function (key,value){
                                //$('#id_'+ key).next() 获取id_mobile 的下一个标签<span>
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        /*
        点击获取验证码的按钮绑定事件
         */
        function bindClickBtnSms(){
            $("#btnSms").click(function (){
                //获取用户手机号，根据输入框内容id获取
                $('.error-msg').empty();
                const mobile = $('#id_mobile').val();

                $.ajax({
                    url:'{% url "web:send_sms" %}',
                    type: 'GET',
                    data: {mobile: mobile, tpl: "login"},
                    dataType: "JSON", //将服务端返回的数据反序列化成字典
                    success: function (res){
                        //ajax 发送成功后，自动执行的函数  res是后端返回的值
                        if(res.status){
                            console.log('发送成功,倒计时60s')
                            sendSmsRemind();
                        }else {
                            //提示错误信息
                            //console.log(res) //{status:False, error:{mobile:["错误信息",]}}
                            $.each(res.error, function (key,value){

                                //$('#id_'+ key).next() 获取id_mobile 的下一个标签<span>
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }
        /*发送短信成功倒计时60秒*/
        function sendSmsRemind(){
            const $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true);

            let time = 60;
            const remind = setInterval(function () {
                $smsBtn.val(time + '秒后重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000);

        }
    </script>
{% endblock %}

web/templates/project_list.html
{% extends 'layout/manage.html' %}
{% block css %}
    <style>
        .project {
            margin-top: 20px;
        }

        .panel-body {
            padding: 0;
            display: flex;
            flex-direction: row;
            justify-content: left;
            align-items: flex-start;
            flex-wrap: wrap;
        }

        .panel-body > .item {
            border-radius: 6px;
            width: 228px;
            border: 1px solid #dddddd;
            margin: 20px 10px;

        }

        .panel-body > .item:hover {
            border: 1px solid #f0ad4e;
        }

        .panel-body > .item > .title {
            height: 104px;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-top-left-radius: 6px;
            border-top-right-radius: 6px;
            font-size: 15px;
            text-decoration: none;
        }

        .panel-body > .item > .info {
            padding: 10px 10px;

            display: flex;
            justify-content: space-between;

            border-bottom-left-radius: 6px;
            border-bottom-right-radius: 6px;
            color: #8c8c8c;

        }

        .panel-body > .item > .info a {
            text-decoration: none;
        }

        .panel-body > .item > .info .fa-star {
            font-size: 18px;
        }

        .color-radio label {
            margin-left: 0;
            padding-left: 0;
        }

        .color-radio input[type="radio"] {
            display: none;
        }

        .color-radio input[type="radio"] + .cycle {
            display: inline-block;
            height: 25px;
            width: 25px;
            border-radius: 50%;
            border: 2px solid #dddddd;
        }

        .color-radio input[type="radio"]:checked + .cycle {
            border: 2px solid black;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid project">
        <div style="margin: 10px 0;">
            <a class="btn btn-primary" data-toggle="modal" data-target="#addModal">
                <i class="fa fa-plus-circle" aria-hidden="true"></i> 新建项目
            </a>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-star" aria-hidden="true"></i> 星标</div>
            <div class="panel-body">
                {% for item in project_dict.star %}
                    <div class="item">
{#                        <a href="{% url 'dashboard' project_id=item.value.id %}" class="title"#}
                        <a href="#" class="title"
                           style="background-color: {{ item.value.get_color_display }};">{{ item.value.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'web:project_unstar' project_type=item.type project_id=item.value.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #f0ad4e;"></i>
                                </a>
                                <span>{{ item.value.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.value.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-list" aria-hidden="true"></i> 我创建的</div>
            <div class="panel-body">
                {% for item in project_dict.my %}
                    <div class="item">
                        <a href="#" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'web:project_star' project_type='my' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading"><i class="fa fa-handshake-o" aria-hidden="true"></i> 我参与的</div>
            <div class="panel-body">
                {% for item in project_dict.join %}
                    <div class="item">
                        <a href="#" class="title"
                           style="background-color: {{ item.get_color_display }};">{{ item.name }}</a>
                        <div class="info">
                            <div>
                                <a href="{% url 'web:project_star' project_type='join' project_id=item.id %}">
                                    <i class="fa fa-star" aria-hidden="true" style="color: #d5d5d5"></i>
                                </a>
                                <span>{{ item.creator.username }}</span>
                            </div>
                            <div>
                                <i class="fa fa-user-o" aria-hidden="true"></i>
                                <span>{{ item.join_count }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>


    <!-- Modal -->
    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建项目</h4>
                </div>
                <div class="modal-body">
                    <form id="addForm">
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                                <span class="error-msg"></span>
                            </div>
                        {% endfor %}

                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSubmit" type="button" class="btn btn-primary">确 定</button>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function () {
            bindSubmit();
        });


        function bindSubmit() {
            $('#btnSubmit').click(function () {

                $.ajax({
                    url: "{% url 'web:project_list' %}",
                    type: "POST",
                    data: $('#addForm').serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        console.log(res);
                        if (res.status) {
                            location.href = location.href;
                            // location.reload()
                        } else {
                            $.each(res.error, function (key, value) {
                                $("#id_" + key).next().text(value[0]);
                            })
                        }
                    }
                })

            })
        }
    </script>
{% endblock %}

web/templates/register.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}注册页{% endblock %}
{% block css %}
<link rel="stylesheet" href="{% static "css/account.css" %}">
    <style>
        .error-message{
            color: red;
            position: absolute;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="account">
        <div class="title">用户注册</div>
        <form id="regForm" method="POST" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                  <div class="form-group">
                  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                     <div class="row">
                          <div class="col-xs-7">
                              {{ field }}
                              <span class="error-message">{{ field.errors.0 }}</span>
                          </div>
                          <div class="col-xs-5">
                              <input id="btnSms" type="button" class="btn btn-default" value="点击获取验证码">
                          </div>
                     </div>
                  </div>
                {% else %}
                   <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                      {{ field }}
                       <span class="error-message"></span>
                  </div>
                {% endif %}
            {% endfor %}
            <div class="row">
                <div class="col-xs-3">
                    <input id="btnSubmit" type="button" class="btn btn-primary" value="注   册">
                </div>
            </div>
        </form>

    </div>

{% endblock %}

{% block js %}
    {#  页面加载完成之后自动执行函数  #}
    <script>
        $(function () {
            bindClickBtnSms();
            bindClickSubmit();
        });

        /*点击注册绑定事件*/
        function bindClickSubmit(){
            $('#btnSubmit').click(function (){
                $('.error-msg').empty();
                //收集表单数据($('#regForm').serialize() 获取所有表单字段的数据 + 获取CSRF tocken)
                //发送数据到后台
                $.ajax({
                    url:"{% url "web:register" %}",
                    type:"POST",
                    data: $('#regForm').serialize(),
                    dataType: "JSON",
                    success:function (res){
                        if(res.status){
                            location.href = res.data;
                        }else {
                            $.each(res.error, function (key,value){
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }

        /*
        点击获取验证码的按钮绑定事件
         */
        function bindClickBtnSms(){
            $("#btnSms").click(function (){
                //获取用户手机号，根据输入框内容id获取
                $('.error-msg').empty();
                const mobile = $('#id_mobile').val();

                $.ajax({
                    url:'{% url "web:send_sms" %}',
                    type: 'GET',
                    data: {mobile: mobile, tpl: "register"},
                    dataType: "JSON", //将服务端返回的数据反序列化成字典
                    success: function (res){
                        //ajax 发送成功后，自动执行的函数  res是后端返回的值
                        if(res.status){
                            console.log('发送成功,倒计时60s')
                            sendSmsRemind();
                        }else {
                            //提示错误信息
                            //console.log(res) //{status:False, error:{mobile:["错误信息",]}}
                            $.each(res.error, function (key,value){

                                //$('#id_'+ key).next() 获取id_mobile 的下一个标签<span>
                                $('#id_' + key).next().text(value[0]);
                            })
                        }
                    }
                })
            })
        }
        /*发送短信成功倒计时60秒*/
        function sendSmsRemind(){
            const $smsBtn = $('#btnSms');
            $smsBtn.prop('disabled', true);

            let time = 60;
            const remind = setInterval(function () {
                $smsBtn.val(time + '秒后重新发送');
                time = time - 1;
                if (time < 1) {
                    clearInterval(remind);
                    $smsBtn.val('点击获取验证码').prop('disabled', false);
                }
            }, 1000);

        }
    </script>
{% endblock %}